# Generated by Django 6.0.5 on 2026-05-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="waypoints",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
